// Code generated by Kitex v0.13.1. DO NOT EDIT.

package kitex_gen

import (
	"context"

	"github.com/cloudwego/prutal"
)

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() { *x = HelloRequest{} }

func (x *HelloRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HelloRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *HelloReply) Reset() { *x = HelloReply{} }

func (x *HelloReply) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HelloReply) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Greeter interface {
	SayHello(ctx context.Context, req *HelloRequest) (res *HelloReply, err error)
}
