// Code generated by Kitex v0.12.0. DO NOT EDIT.

package greeter

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	kitex_gen "github.com/luvx21/coding-go/coding-usage/rpc/kitex/kitex_gen"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SayHello": kitex.NewMethodInfo(
		sayHelloHandler,
		newSayHelloArgs,
		newSayHelloResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	greeterServiceInfo                = NewServiceInfo()
	greeterServiceInfoForClient       = NewServiceInfoForClient()
	greeterServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return greeterServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return greeterServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return greeterServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Greeter"
	handlerType := (*kitex_gen.Greeter)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "proto",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.0",
		Extra:           extra,
	}
	return svcInfo
}

func sayHelloHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.HelloRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.Greeter).SayHello(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SayHelloArgs:
		success, err := handler.(kitex_gen.Greeter).SayHello(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SayHelloResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSayHelloArgs() interface{} {
	return &SayHelloArgs{}
}

func newSayHelloResult() interface{} {
	return &SayHelloResult{}
}

type SayHelloArgs struct {
	Req *kitex_gen.HelloRequest
}

func (p *SayHelloArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.HelloRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SayHelloArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SayHelloArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SayHelloArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SayHelloArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.HelloRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SayHelloArgs_Req_DEFAULT *kitex_gen.HelloRequest

func (p *SayHelloArgs) GetReq() *kitex_gen.HelloRequest {
	if !p.IsSetReq() {
		return SayHelloArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SayHelloArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SayHelloArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SayHelloResult struct {
	Success *kitex_gen.HelloReply
}

var SayHelloResult_Success_DEFAULT *kitex_gen.HelloReply

func (p *SayHelloResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.HelloReply)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SayHelloResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SayHelloResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SayHelloResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SayHelloResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.HelloReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SayHelloResult) GetSuccess() *kitex_gen.HelloReply {
	if !p.IsSetSuccess() {
		return SayHelloResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SayHelloResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.HelloReply)
}

func (p *SayHelloResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SayHelloResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SayHello(ctx context.Context, Req *kitex_gen.HelloRequest) (r *kitex_gen.HelloReply, err error) {
	var _args SayHelloArgs
	_args.Req = Req
	var _result SayHelloResult
	if err = p.c.Call(ctx, "SayHello", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
