// Code generated by Kitex v0.13.1. DO NOT EDIT.
package greeter

import (
	server "github.com/cloudwego/kitex/server"
	kitex_gen "github.com/luvx21/coding-go/coding-usage/rpc/kitex/kitex_gen"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kitex_gen.Greeter, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler kitex_gen.Greeter, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
