@host = localhost:58090

###
GET http://{{host}}

###
GET http://{{host}}/app/:path

###
GET http://{{host}}/app/healthyCheck

###
POST http://{{host}}/app/syncCookie2Turso
Content-Type: application/json

{
  "hosts": [
    ".weibo.com",
    "weibo.com",
    ".bilibili.com",
    "bilibili.com"
  ]
}

###
GET http://{{host}}/redirect?url=xxx

###
GET http://{{host}}/user/:username

###
GET http://{{host}}/bili/pull/season?seasonId=0

###
GET http://{{host}}/bili/pull/up/video?mid=0

###
GET http://{{host}}/weibo/pull/user?uid=0

###
GET http://{{host}}/weibo/pull/group

###
GET http://{{host}}/weibo/rss/:uid

###
GET http://{{host}}/weibo/rss/delete/:id

### useful
POST http://{{host}}/app/useful/compare
Content-Type: application/json

{
    "left": [
        1,
        2,
        3
    ],
    "right": [
        2,
        3,
        4
    ]
}